Rishi: Check fpga-network/minirocket/src/minirocket.cpp for the streaming convolution

diff --git a/fpga-network/Makefile b/fpga-network/Makefile
--- a/fpga-network/Makefile
+++ b/fpga-network/Makefile
@@ -1,137 +1,171 @@
-#
-# Copyright 2019-2021 Xilinx, Inc.
-#
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#     http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
-# makefile-generator v1.0.3
-#
+SHELL=/bin/bash
 
-SHELL := /bin/bash
-
-############################## Help Section ##############################
 .PHONY: help
 
-help::
-	$(ECHO) "Makefile Usage:"
-	$(ECHO) "  make build PLATFORM=<FPGA platform>"
-	$(ECHO) "      Command to generate the design for specified Target and Shell."
-	$(ECHO) ""
-	$(ECHO) "  make clean "
-	$(ECHO) "      Command to remove the generated non-hardware files."
-	$(ECHO) ""
-	$(ECHO) "  make cleanall"
-	$(ECHO) "      Command to remove all the generated files."
-	$(ECHO) ""
+help:
+	@echo "Makefile Usage:"
+	@echo "  make all DEVICE=<FPGA platform> INTERFACE=<CMAC Interface> DESIGN=<design name>"
+	@echo "      Command to generate the xo for specified device and Interface."
+	@echo "      By default, DEVICE=xilinx_u280_xdma_201920_3, INTERFACE=0  DESIGN=benchmark"
+	@echo "      DESIGN also supports the string basic"
+	@echo ""
+	@echo "  make clean "
+	@echo "      Command to remove the generated non-hardware files."
+	@echo ""
+	@echo "  make distclean"
+	@echo "      Command to remove all the generated files in the current directory"
+	@echo ""
+	@echo "  make distcleanall"
+	@echo "      Command to remove all the generated in the current directory and one level down"
+	@echo ""
 
 
-############################## Setting up Project Variables ##############################
-# Points to top directory of Git repository
-MK_PATH := $(abspath $(lastword $(MAKEFILE_LIST)))
-COMMON_REPO ?= $(shell bash -c 'export MK_PATH=$(MK_PATH); echo $${MK_PATH}')
-PWD = $(shell readlink -f .)
-XF_PROJ_ROOT = $(shell readlink -f $(COMMON_REPO))
+DEVICE ?= xilinx_u280_xdma_201920_3
+INTERFACE ?= 0
+DESIGN ?= benchmark
+XCLBIN_NAME ?= vnx_$(DESIGN)_if$(INTERFACE)
+MAX_SOCKETS ?= 16
 
-TARGET := hw
-
-IPREPOPATH ?= ./iprepo
-export IPREPOPATH
-include ./utils.mk
-include ./opencl.mk
-
-
-XSA := 
-ifneq ($(PLATFORM), )
-XSA := $(call device2xsa, $(PLATFORM))
-endif
-
+XSA := $(strip $(patsubst %.xpfm, % , $(shell basename $(DEVICE))))
 TEMP_DIR := _x.$(XSA)
-BUILD_DIR := ./build_dir.$(TARGET).$(XSA)
-NETLAYERDIR := ./NetLayers/
-CMACDIR := ./cmac_krnl/
+VPP := $(XILINX_VITIS)/bin/v++
+CLFLAGS += -t hw --platform $(DEVICE) --save-temps
 
-MINIROCKET_XO_REPO := ./build/iprepo
-NETLAYER_XO_REPO := $(NETLAYERDIR)$(TEMP_DIR)
+BUILD_DIR := ./$(DESIGN).intf$(INTERFACE).$(XSA)
+BINARY_CONTAINERS = $(BUILD_DIR)/${XCLBIN_NAME}.xclbin
+
+NETLAYERDIR = NetLayers/
+CMACDIR     = Ethernet/
+BASICDIR    = Basic_kernels/
+BENCHMARDIR = Benchmark_kernel/
+
 NETLAYERHLS = 100G-fpga-network-stack-core
-CMAC_XO_REPO := $(CMACDIR)$(TEMP_DIR)
 
-HLS_IP_FOLDER  = $(shell readlink -f ./$(NETLAYERDIR)$(NETLAYERHLS)/synthesis_results_HBM)
-LIST_REPOS := --user_ip_repo_paths $(HLS_IP_FOLDER) --user_ip_repo_paths $(IPREPOPATH)
+POSTSYSLINKTCL ?= $(shell readlink -f ./Ethernet/post_sys_link.tcl)
+SWITCH_IP_FOLDER ?= $(shell readlink -f ./$(BENCHMARDIR)/packaged_kernel_switch_wrapper_$(XSA))
 
-HOST_DIR := ./host
+IPREPO = ./build/iprepo
 
-VPP := v++
-CXXFLAGS += $(opencl_CXXFLAGS) -Wall -O0 -g -std=c++1y
-LDFLAGS += $(opencl_LDFLAGS)
+LIST_XO = $(NETLAYERDIR)$(TEMP_DIR)/networklayer.xo
+LIST_XO += $(IPREPO)/minirocket_inference.xo
 
-INCLUDES = ./src
+CONFIGFLAGS = --config config.cfg
+#CONFIGFLAGS += --kernel_frequency 280
 
-MINIROCKET_KRNL := minirocket_inference
-NETLAYER_KRNL := networklayer
-CMAC_KRNL:=cmac_krnl
-include config_cmac.mk
-XOs += $(MINIROCKET_XO_REPO)/$(MINIROCKET_KRNL).xo $(NETLAYER_XO_REPO)/$(NETLAYER_KRNL).xo $(CMAC_XO_REPO)/${CMAC_KRNL}.xo
-
-############################## Setting up Host Variables ##############################
-
-HOST_SRCS += $(HOST_DIR)/src/minirocket_host.cpp $(HOST_DIR)/src/minirocket_loader.cpp
-CXXFLAGS += -fmessage-length=0 -I$(INCLUDES) -I${HOST_DIR}/include
-LDFLAGS += -lrt -lstdc++ 
-
-############################## Setting up Kernel Variables ##############################
-VPP_FLAGS += -t $(TARGET) --platform $(PLATFORM) --save-temps -I$(INCLUDES) --config config.cfg
-ifneq ($(TARGET), hw)
-	VPP_FLAGS += -g
-endif
-
-
-
-############################## Declaring Binary Containers ##############################
-XLCBIN += $(BUILD_DIR)/krnl.xclbin
-EXECUTABLE = ./minirocket_host
-
-############################## Setting Targets ##############################
-CP = cp -rf
-
-.PHONY: all clean cleanall 
-all: check-platform check-device check-vitis $(EXECUTABLE) $(XLCBIN) 
-
-.PHONY: host
-host: $(EXECUTABLE)
-
-.PHONY: build
-build: check-vitis check-device $(XLCBIN)
-
-.PHONY: xclbin
-xclbin: build
-
-############################## Setting Rules for Binary Containers (Building Kernels) ##############################
-
-$(XLCBIN): $(XOs)
-	mkdir -p $(BUILD_DIR)
-ifeq ($(HOST_ARCH), x86)
-	$(VPP) $(VPP_FLAGS) -l $(VPP_LDFLAGS) $(LIST_REPOS) --temp_dir $(TEMP_DIR) -o'$(BUILD_DIR)/krnl.link.xclbin' $(+)
-	$(VPP) -p $(BUILD_DIR)/krnl.link.xclbin -t $(TARGET) --platform $(PLATFORM) --package.out_dir $(PACKAGE_OUT) -o $(BUILD_DIR)/krnl.xclbin
+# Include cmac kernel depending on the interface
+ifeq (3,$(INTERFACE))
+	LIST_XO += $(CMACDIR)$(TEMP_DIR)/cmac_0.xo
+	LIST_XO += $(CMACDIR)$(TEMP_DIR)/cmac_1.xo
 else
-	$(VPP) $(VPP_FLAGS) -l $(VPP_LDFLAGS) $(LIST_REPOS) --temp_dir $(TEMP_DIR) -o'$(BUILD_DIR)/krnl.xclbin' $(+)
+	LIST_XO += $(CMACDIR)$(TEMP_DIR)/cmac_$(INTERFACE).xo
 endif
 
-############################## Cleaning Rules ##############################
+LIST_REPOS = 
+
+# Include application kernels depending on the design
+# ifeq (benchmark,$(DESIGN))
+# 	LIST_XO += $(BENCHMARDIR)$(TEMP_DIR)/traffic_generator.xo
+# 	LIST_XO += $(BENCHMARDIR)$(TEMP_DIR)/collector.xo
+# 	LIST_XO += $(BENCHMARDIR)$(TEMP_DIR)/switch_wrapper.xo
+# 	LIST_REPOS += --user_ip_repo_paths $(SWITCH_IP_FOLDER)
+# else
+# 	LIST_XO += $(BASICDIR)$(TEMP_DIR)/krnl_mm2s.xo
+# 	LIST_XO += $(BASICDIR)$(TEMP_DIR)/krnl_s2mm.xo
+# endif
+
+# Linker parameters
+# Linker userPostSysLinkTcl param
+ifeq (u5,$(findstring u5, $(DEVICE)))
+	HLS_IP_FOLDER  = $(shell readlink -f ./$(NETLAYERDIR)$(NETLAYERHLS)/synthesis_results_HBM)
+else ifeq (u280,$(findstring u280, $(DEVICE)))
+	HLS_IP_FOLDER  = $(shell readlink -f ./$(NETLAYERDIR)$(NETLAYERHLS)/synthesis_results_HBM)
+else ifeq (u2,$(findstring u2, $(DEVICE)))
+	HLS_IP_FOLDER  = $(shell readlink -f ./$(NETLAYERDIR)$(NETLAYERHLS)/synthesis_results_noHBM)
+endif
+
+LIST_REPOS += --user_ip_repo_paths $(HLS_IP_FOLDER)
+
+.PHONY: all clean distclean distcleanall
+all: check-devices check-vitis check-xrt check-design check-interface create-conf-file $(BINARY_CONTAINERS)
+
 # Cleaning stuff
 clean:
-	-$(RMDIR) $(EXECUTABLE) $(XCLBIN)/{*sw_emu*,*hw_emu*} 
-	-$(RMDIR) profile_* TempConfig system_estimate.xtxt *.rpt *.csv 
-	-$(RMDIR) src/*.ll *v++* .Xil emconfig.json dltmp* xmltmp* *.log *.jou *.wcfg *.wdb
+	rm -rf *v++* *.log *.jou *.str
 
-cleanall: clean
-	-$(RMDIR) build_dir* sd_card*
-	-$(RMDIR) package.*
-	-$(RMDIR) _x* *xclbin.run_summary qemu-memory-_* emulation _vimage pl* start_simulation.sh *.xclbin packaged_kernel_* tmp_kernel_*
+distclean: clean
+	rm -rf _x* *.tmp.ini .Xil benchmark*/ basic*/ .ipcache/
+
+distcleanall: distclean
+	make -C $(NETLAYERDIR) distcleanall
+	make -C $(CMACDIR) distclean
+	make -C $(BASICDIR) distclean
+	make -C $(BENCHMARDIR) distclean
+
+
+# Building xclbin
+$(BUILD_DIR)/${XCLBIN_NAME}.xclbin: $(LIST_XO)
+	mkdir -p $(BUILD_DIR)
+	$(VPP) $(CLFLAGS) $(CONFIGFLAGS) --temp_dir $(BUILD_DIR) -l -o'$@' $^ $(LIST_REPOS)
+
+$(BASICDIR)$(TEMP_DIR)/%.xo: $(BASICDIR)src/*.cpp
+	make -C $(BASICDIR) all DEVICE=$(DEVICE) -j3
+
+$(BENCHMARDIR)$(TEMP_DIR)/%.xo: $(BENCHMARDIR)src/*
+	make -C $(BENCHMARDIR) all DEVICE=$(DEVICE) -j3
+
+$(CMACDIR)$(TEMP_DIR)/%.xo:
+	make -C $(CMACDIR) all DEVICE=$(DEVICE) INTERFACE=$(INTERFACE)
+
+$(NETLAYERDIR)$(TEMP_DIR)/%.xo:
+	cd ./$(NETLAYERDIR)$(NETLAYERHLS) && git checkout -- .
+	make -C $(NETLAYERDIR) all DEVICE=$(DEVICE) MAX_SOCKETS=$(MAX_SOCKETS)
+
+check-devices:
+ifndef DEVICE
+	$(error DEVICE not set. Please set the DEVICE properly and rerun. Run "make help" for more details.)
+endif
+
+#Checks for XILINX_VITIS
+check-vitis:
+ifndef XILINX_VITIS
+	$(error XILINX_VITIS variable is not set, please set correctly and rerun)
+endif
+
+#Checks for XILINX_XRT
+check-xrt:
+ifndef XILINX_XRT
+	$(error XILINX_XRT variable is not set, please set correctly and rerun)
+endif
+
+#Check if the design name is supported
+check-design:
+	@if [[ ($(DESIGN) != "benchmark") && ($(DESIGN) != "basic") ]]; then\
+		echo "DESIGN=$(DESIGN) is not supported!";\
+		exit 1;\
+	fi
+
+check-interface:
+	@if [[ ($(XSA) =~ "u50") && ($(INTERFACE) != 0) ]]; then\
+		echo "Platform $(XSA) only has INTERFACE=0!";\
+		exit 1;\
+	fi
+	@if [[ ($(INTERFACE) != 0) && ($(INTERFACE) != 1) && ($(INTERFACE) != 3) ]]; then\
+		echo "Interface $(INTERFACE) is not supported in platform $(XSA)!";\
+		exit 1;\
+	fi
+
+#Create configuration file for current design and settings
+create-conf-file:
+	cp config.cfg.in config.cfg
+	echo "" >> config.cfg
+	echo "" >> config.cfg
+	echo "[advanced]" >> config.cfg
+	echo "param=compiler.userPostSysLinkOverlayTcl=$(POSTSYSLINKTCL)" >> config.cfg
+	echo "#param=compiler.worstNegativeSlack=-2" >> config.cfg
+	echo "#param=compiler.errorOnHoldViolation=false" >> config.cfg
+	echo "[vivado]" >> config.cfg
+	echo "prop=run.impl_1.strategy=Performance_NetDelay_low" >> config.cfg
+	@if [[ $(DEVICE) = *"u5"* ]]; then\
+		sed -i 's/SLR2/SLR1/g' config.cfg;\
+		sed -i 's/DDR\[1\]/HBM\[0\]/g' config.cfg;\
+	fi
